format = '''
[â”](247)[â”](246)[â”](245)[â”](244)[â”](243)[â”](242)[â”«](241)$username$hostname[â”£](241)[â”](240)[â”](239)[â”](238)[â”](237)[â•¾](236)[â•¶](236) $directory$fill$docker_context$package$golang$java$cmake$julia$kotlin$lua$nodejs$python$ruby$rust$git_branch $git_status${custom.ssh}
[â”•](248)[â”](249)[â¯](250)$character'''
 
right_format='''$jobs$cmd_duration$battery'''

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = " [Î»](254)"
error_symbol = ' [âœ—](bold red) '

[cmd_duration]
min_time = 500
show_milliseconds = true
format=' [ó±«$duration]($style) '
style="bold yellow"

[java]
symbol = "ó°¬·"
style="red"
format="via [${symbol} (${version} )](208)($style)"

[lua]
style="#7FFFD4"

[cmake]
symbol = "î™³"
format="via [${symbol} (${version} )]($style)"

[kubernetes]
format = 'context: [âˆ $context \($namespace\)](bold cyan) '
disabled = false
# [kubernetes.context_aliases]
# "dev.local.cluster.k8s" = "dev"

[memory_usage]
format = "with$symbol [${ram} ${ram_pct}( | ${swap} ${swap_pct})]($style) "
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[docker_context]
format = "[ó°¡¨ $context](blue bold) "
disabled = false

[directory]
truncation_length = 7
truncation_symbol = "â€¦/"

[username]
style_user = "252"
style_root = "red"
format = "[$user]($style)[ó°¥](241)"
disabled = false

[fill]
symbol = ' '
style = ''

[time]
disabled = false
format = '[\[ $time \]]($style) '

[hostname]
style = "purple bold"
ssh_only = false
ssh_symbol = 'ó°¹‘'
format = '[$hostname]($style)'
trim_at = "."
disabled = false

[custom.ssh]
when = 'test "$SSH_CONNECTION" != ""'
symbol = 'ó°¹‘'
style = "250"
format = '[$symbol]($style)'

[status]
style = "red"
symbol = "ï”° "
format = '[\[$symbol$status\]]($style) '
disabled = false

[git_branch]
always_show_remote = true
style = "bold blue"
format = '[â”€](245)[â•¼â”](246)[â”«](247)[$symbol$branch(:$remote_branch)]($style)[â”£](247)[â”â•¾](246)[â”€](245)'

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡ğŸ˜µ${ahead_count}â‡£${behind_count}"
behind = "â‡£ğŸ˜°${count}"
conflicted = "ï€¤ "
untracked = "ó° —"
stashed = "ó°½„ "
modified = "ï„ "
staged = 'îœ©${count}'
renamed = "ï‘š"
deleted ="ó°†´"
style = "140"
format = '[$all_status$ahead_behind]($style)'

[package]
style = "208"
symbol = 'î¬©'
format = "[â”€](238)[â•¼â”](239)[â”«](242)[$symbol $version]($style)[â”€](237)"

[rust]
style = "208"
symbol = 'î¨'
format ="[$symbol $version]($style)[â”£](242)[â”â•¾](239)[â”€](238) "

[golang]
symbol = 'î˜§'
format = "[â”€](244)[â•¼â”](243)[â”«](242)[$symbol $version](bold cyan)[â”£](242)[â”â•¾](243)[â”€](244) "

[jobs]
symbol = "ó°¦–"
format = "[$symbol$number]($style)"

[battery]
full_symbol = "ó°¹"
charging_symbol = "ó°š¥ "
discharging_symbol = "ó°º "
disabled = false

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
discharging_symbol = 'ó°º '
style = "red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 20
discharging_symbol = 'ó°» '
style = "166"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
discharging_symbol = 'ó°¼ '
style = "yellow"

[[battery.display]]
threshold = 40
discharging_symbol = 'ó°½ '
style = "172"

[[battery.display]]
threshold = 50
discharging_symbol = 'ó°¾ '
style = "170"

[[battery.display]]
threshold = 60
discharging_symbol = 'ó°¿ '
style = "097"

[[battery.display]]
threshold = 70
discharging_symbol = 'ó°‚€ '
style = "098"

[[battery.display]] 
threshold = 80
discharging_symbol = 'ó°‚ '
style = "099"

[[battery.display]] 
threshold = 90
discharging_symbol = 'ó°‚‚ '
style = "purple"

[[battery.display]]
threshold = 100
discharging_symbol = 'ó°‚‚ '
style = "green"

[nix_shell]
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [â˜ƒï¸ $state( \($name\))](bold blue) '
